// Description: WordPress API functions

import site from "@/site";
import { failure, Result, success } from "./util";

// Used to fetch data from a WordPress site using the WordPress REST API
const baseUrl = `${process.env.WORDPRESS_URL}/graphql`;

if (!baseUrl) {
  throw new Error("WORDPRESS_URL environment variable is not defined");
}

export interface WordPressResponse<T> {
  data: T;
}

async function wordpressFetch<T>(query?: string): Promise<Result<T>> {
  try {
    const response = await fetch(baseUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: query }),
    });

    if (!response.ok) {
      return failure(`WordPress API request failed: ${response.statusText}`);
    }

    const res = (await response.json()) as WordPressResponse<T>;

    return success(res.data);
  } catch (e) {
    console.error(e);
    if (e instanceof Error) {
      return failure(e.message);
    }
    return failure("An error occured");
  }
}

export async function getPageBySlug(slug: string) {
  const postData = /* GraphQL */ `
    nodes {
       ... on Post {
      id
      slug
      title
      author {
        node {
          firstName
          lastName
          avatar {
            url
          }
        }
      }
      categories(first: 1) {
        nodes {
          name
        }
      }
      featuredImage {
        node {
          sourceUrl
        }
      }
      additionalPostData {
        excerpt
      }
    }
  }
  `;
  const query = /* GraphQL */ `
    query GetDynamicPage {
      dynamicPageBy(id: "cG9zdDoxMDM1") {
        id
        slug
        title
        pageData {
          blocks {
            featured {
              ${postData}
            }
            primary {
              ${postData}
            }
            secondary {
              ${postData}
            }
          }
        }
      }
    }
  `;

  const resp = await wordpressFetch<WordPressGetDynamicPageResult>(query);
  return resp;
}

export async function getPostBySlug(slug: string) {
  const query = /* GraphQL */ `
  query GetPost {
    postBy(slug: "${slug}") {
    id
    title
    content
    additionalPostData {
      excerpt
    }
    featuredImage {
      node {
        sourceUrl
        altText
      }
    }
    author {
      node {
        firstName
        lastName
        avatar {
          url
        }
      }
    }
    categories(first: 1) {
      nodes {
        name
      }
    }
  }
}
`;

  const resp = await wordpressFetch<WordPressGetPostResult>(query);
  return resp;
}

export function getLinkFromPost(post: WordPressPost) {
  return `/articles/${post.slug}`;
}

export function getCategoryFromPost(post: WordPressPost) {
  if (
    !post.categories ||
    !Array.isArray(post.categories.nodes) ||
    post.categories.nodes.length < 1
  ) {
    return DEFAULT_CATEGORY;
  }

  if (post.categories.nodes[0].name === "Uncategorized") {
    return DEFAULT_CATEGORY;
  }

  return post.categories.nodes[0].name;
}

export function getImageSrcFromPost(post: WordPressPost) {
  if (!post.featuredImage) {
    console.log({ post });
    throw Error(`Need a default image ${post.title}`);
  }
  return post.featuredImage.node;
}

export function getAuthorFromPost(post: WordPressPost): WordPressAuthorClean {
  let author = post.author?.node;

  if (!author || !author.firstName) {
    return DEFAULT_AUTHOR;
  }

  let firstName = author.firstName;
  let lastName = author?.lastName ? author.lastName : "";
  let sourceUrl = author.avatar?.url
    ? author.avatar.url
    : DEFAULT_AUTHOR.avatar.sourceUrl;
  let altText = `${firstName} portrait`;

  return {
    firstName,
    lastName,
    avatar: {
      sourceUrl,
      altText,
    },
  };
}

export function getExcerptFromPost(post: WordPressPost) {
  let excerpt = post?.additionalPostData?.excerpt;
  if (!excerpt) {
    return site.description;
  }

  return excerpt;
}

export function getAvatarFromAuthor(author: WordPressAuthor) {
  if (!author.avatar || !author.avatar.url) {
    console.error("NEED A DEFAULT IMAGE FOR AUTHORS");
    return { url: "test-url" };
  }

  return author.avatar;
}

export interface WordPressGetPostResult {
  postBy: WordPressPost;
}

export interface WordPressPost {
  /** Autogenerated post id */
  id: string;
  /** Post title*/
  title: string;
  /** Post html content*/
  content: string;
  /** Post slug */
  slug: string;
  /** Metadata */
  additionalPostData?: {
    /** Metadata Description */
    excerpt: string;
  };

  featuredImage?: {
    node: WordPressImageData;
  };
  author?: {
    node: WordPressAuthor;
  };
  categories?: {
    nodes: WordPressCategoryNode[];
  };
}

export interface WordPressGetDynamicPageResult {
  dynamicPageBy: {
    pageData: {
      blocks: {
        featured: WordPressPageBlock;
        primary: WordPressPageBlock;
        secondary: WordPressPageBlock;
      };
    };
  };
}

export interface WordPressPageBlock {
  nodes: WordPressPost[];
}

export interface WordPressCategoryNode {
  name: string;
}

export interface WordPressImageData {
  sourceUrl: string;
  altText: string;
}

export interface WordPressAuthor {
  firstName?: string;
  lastName?: string;
  avatar?: WordPressAvatar;
}

export interface WordPressAuthorClean {
  firstName: string;
  lastName: string;
  avatar: WordPressAvatarClean;
}

export interface WordPressAvatar {
  url?: string;
}

export interface WordPressAvatarClean extends WordPressImageData {}

const DEFAULT_CATEGORY = "Article";

const DEFAULT_AUTHOR: WordPressAuthorClean = {
  firstName: "SUSU",
  lastName: "",
  avatar: {
    altText: "SUSU portrait",
    sourceUrl:
      "http://susu.flywheelsites.com/wp-content/uploads/2025/11/SUSU-Logo.png",
  },
};
