// Description: WordPress API functions

import { failure, Result, success } from "./util";

// Used to fetch data from a WordPress site using the WordPress REST API
const baseUrl = `${process.env.WORDPRESS_URL}/graphql`;

if (!baseUrl) {
  throw new Error("WORDPRESS_URL environment variable is not defined");
}

export interface WordPressResponse<T> {
  data: T;
}

async function wordpressFetch<T>(query?: string): Promise<Result<T>> {
  try {
    const response = await fetch(baseUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: query }),
    });

    if (!response.ok) {
      return failure(`WordPress API request failed: ${response.statusText}`);
    }

    const res = (await response.json()) as WordPressResponse<T>;
    return success(res.data);
  } catch (e) {
    console.error(e);
    if (e instanceof Error) {
      return failure(e.message);
    }
    return failure("An error occured");
  }
}

export async function getPostBySlug(slug: string) {
  const query = /* GraphQL */ `
  query GetPost {
    postBy(slug: "${slug}") {
    id
    title
    content
    featuredImage {
      node {
        sourceUrl
        altText
      }
    }
    categories(first: 1) {
      nodes {
        name
      }
    }
  }
}
`;

  const resp = await wordpressFetch<WordPressGetPostResult>(query);
  return resp;
}

export function getCategoryFromPost(post: WordPressPost) {
  if (
    !post.categories ||
    !Array.isArray(post.categories.nodes) ||
    post.categories.nodes.length < 1
  ) {
    return DEFAULT_CATEGORY;
  }

  return post.categories.nodes[0].name;
}

export function getImageSrcFromPost(post: WordPressPost) {
  if (!post.featuredImage) {
    console.log({ post });
    throw Error("Need a default image");
  }
  return post.featuredImage.node;
}

export interface WordPressGetPostResult {
  postBy: WordPressPost;
}

export interface WordPressPost {
  /** Autogenerated post id */
  id: string;
  /** Post title*/
  title: string;
  /** Post html content*/
  content: string;
  featuredImage?: {
    node: WordPressImage;
  };
  categories?: {
    nodes: WordPressCategoryNode[];
  };
}

export interface WordPressCategoryNode {
  name: string;
}

export interface WordPressImage {
  sourceUrl: string;
  altText: string;
}

const DEFAULT_CATEGORY = "Uncategorized";
